# SPRING CONFIG
spring:
  application:
    name: Spring-Data-JPA

  datasource: 
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring_data_jpa?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: 'projetosUser'
    password: '@projetos#'

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update    # none, validate, update, create-drop
    properties:
      hibernate:

  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
  file:
    #path: /var/tmp
    name: logging_spring-data-jpa.log

  level: # Log Level: ERROR, WARN, INFO, DEBUG, TRACE 
    #root: "WARN" 
    root: "INFO"
    '[org.hibernate]': "DEBUG"
    #'[org.hibernate.SQL]': "DEBUG"
    '[br.com.zuco]': "DEBUG"
